info:
  name: products add
  type: http
  seq: 11

http:
  method: POST
  url: "{{BASE_URL}}/api/products"
  headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJpYXQiOjE3ODU4MzM4MzEsImV4cCI6MTc4NjQzODYzMX0.elBhmdtLQ5xGGoz715bGeLGWqJFX0uqAMuOlbnvkows
  body:
    type: json
    data: |-
      {
        "name": "Business Card2",
        "slug": "business-card2",
        "shortDescription": "Professional business card printing",
        "description": {
          "heroImage": 1,
          "gallery": [2, 3, 4],
          "blocks": [
            {
              "type": "paragraph",
              "text": "High-quality business card printing."
            }
          ]
        },
        "status": "ACTIVE",
        "featured": true,
        "seo": {
          "title": "Business Card Printing",
          "description": "Order professional business cards.",
          "keywords": [
            "business card",
            "printing"
          ],
          "robots": "index,follow",
          "ogImageId": 1
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
