info:
  name: Settings Seo
  type: http
  seq: 5

http:
  method: PUT
  url: "{{BASE_URL}}/api/settings/seo"
  headers:
    - name: Authorization
      value: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiYWRtaW5AdGVzdC5jb20iLCJpYXQiOjE3ODU4MzM4MzEsImV4cCI6MTc4NjQzODYzMX0.elBhmdtLQ5xGGoz715bGeLGWqJFX0uqAMuOlbnvkows
  body:
    type: json
    data: |-
      {
        "value": {
          "defaultTitle": "Starter Platform",
          "titleTemplate": "%s | Starter Platform",
          "defaultDescription": "Default website description",
          "defaultOgImageId": null
        }
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
